### ISSUE TITLE
Create shared context to "when user is not authenticated"

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/rails_boilerplate#215]

**Comment by valmirosjunior** [comment]
I'm getting  this problem, below when I run Rspec tests:


```shell
Failures:

  1) FetchSchools.call when setup is not valid returns error object
     Failure/Error: response = Faraday.get(FETCH_SCHOOLS_URL, params)
     
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET https://api.data.gov/ed/collegescorecard/v1/schools?api_key=find_it_here_https://github.com/RTICWDT/open-data-maker/blob/master/API.md&fields=id,school.name,location&page=0&school.name=The%20best%20school with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Faraday v2.9.0'}
     
       You can stub this request with the following snippet:
     
       stub_request(:get, "https://api.data.gov/ed/collegescorecard/v1/schools?api_key=find_it_here_https://github.com/RTICWDT/open-data-maker/blob/master/API.md&fields=id,school.name,location&page=0&school.name=The%20best%20school").
         with(
           headers: {
          'Accept'=>'*/*',
          'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
          'User-Agent'=>'Faraday v2.9.0'
           }).
         to_return(status: 200, body: "", headers: {})
     
       ============================================================
     # /usr/local/bundle/gems/webmock-3.23.1/lib/webmock/http_lib_adapters/net_http.rb:106:in `request'
     # /usr/local/bundle/gems/faraday-net_http-3.1.0/lib/faraday/adapter/net_http.rb:113:in `block in request_with_wrapped_block'
     # /usr/local/bundle/gems/webmock-3.23.1/lib/webmock/http_lib_adapters/net_http.rb:116:in `start_without_connect'
     # /usr/local/bundle/gems/webmock-3.23.1/lib/webmock/http_lib_adapters/net_http.rb:143:in `start'
     # /usr/local/bundle/gems/faraday-net_http-3.1.0/lib/faraday/adapter/net_http.rb:112:in `request_with_wrapped_block'
     # /usr/local/bundle/gems/faraday-net_http-3.1.0/lib/faraday/adapter/net_http.rb:102:in `perform_request'
     # /usr/local/bundle/gems/faraday-net_http-3.1.0/lib/faraday/adapter/net_http.rb:66:in `block in call'
     # /usr/local/bundle/gems/faraday-2.9.0/lib/faraday/adapter.rb:45:in `connection'
     # /usr/local/bundle/gems/faraday-net_http-3.1.0/lib/faraday/adapter/net_http.rb:65:in `call'
     # /usr/local/bundle/gems/faraday-2.9.0/lib/faraday/request/url_encoded.rb:25:in `call'
     # /usr/local/bundle/gems/faraday-2.9.0/lib/faraday/rack_builder.rb:152:in `build_response'
     # /usr/local/bundle/gems/faraday-2.9.0/lib/faraday/connection.rb:444:in `run_request'
     # /usr/local/bundle/gems/faraday-2.9.0/lib/faraday/connection.rb:200:in `get'
     # /usr/local/bundle/gems/faraday-2.9.0/lib/faraday.rb:145:in `method_missing'
     # ./app/actors/fetch_schools.rb:19:in `fetch_schools'
     # ./app/actors/fetch_schools.rb:13:in `call'
     # /usr/local/bundle/gems/service_actor-3.9.1/lib/service_actor/core.rb:52:in `_call'
     # /usr/local/bundle/gems/service_actor-3.9.1/lib/service_actor/checkable.rb:23:in `_call'
     # /usr/local/bundle/gems/service_actor-3.9.1/lib/service_actor/defaultable.rb:61:in `_call'
     # /usr/local/bundle/gems/service_actor-3.9.1/lib/service_actor/failable.rb:39:in `_call'
     # /usr/local/bundle/gems/service_actor-3.9.1/lib/service_actor/valuable.rb:33:in `_call'
     # /usr/local/bundle/gems/service_actor-3.9.1/lib/service_actor/core.rb:18:in `call'
     # /usr/local/bundle/gems/service_actor-3.9.1/lib/service_actor/core.rb:28:in `result'
     # ./spec/actors/fetch_schools_spec.rb:32:in `block (3 levels) in <top (required)>'
     # ./spec/actors/fetch_schools_spec.rb:63:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'

Finished in 0.82827 seconds (files took 1.26 seconds to load)
55 examples, 1 failure

Failed examples:

rspec ./spec/actors/fetch_schools_spec.rb:62 # FetchSchools.call when setup is not valid returns error object
```

**Comment by edimossilva** [comment]
@valmirosjunior , I believe this is happening due to some missing env var
